# Generated by Django 6.1 on 2026-08-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='本地原名')),
                ('local_name', models.CharField(max_length=255, verbose_name='本地存储名')),
                ('qiniu_key', models.CharField(max_length=255, unique=True, verbose_name='七牛云对象名')),
                ('cdn_url', models.URLField(blank=True, max_length=512, verbose_name='CDN 链接')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME 类型')),
                ('status', models.CharField(choices=[('active', '正常'), ('deleted', '已删除')], default='active', max_length=16, verbose_name='状态')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
            ],
            options={
                'verbose_name': '图片资源',
                'verbose_name_plural': '图片资源',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
