# Generated by Django 6.1 on 2026-09-04 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_storageconfig_and_asset_changes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageasset',
            name='cdn_url',
            field=models.URLField(blank=True, max_length=512, verbose_name='访问链接'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='object_key',
            field=models.CharField(max_length=255, unique=True, verbose_name='图床对象名'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=40, verbose_name='昵称')),
                ('avatar', models.FileField(blank=True, upload_to='avatars/', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
