# Generated by Django 6.1 on 2026-09-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_imageasset_cdn_url_alter_imageasset_object_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='演示账号'),
        ),
    ]
